### ISSUE TITLE
There is no current event loop in thread 'Thread-7'

### ISSUE THREAD

**Issue by alfiedouglas-tewke** [bigbadblunt/lightwave2#2]
I am trying to execute the non-async methods on a callback for a mqtt subsciption. However as this sometimes creates a new thread I get the error:

`There is no current event loop in thread 'Thread-7'.`

I have attempted to fix this by adding the following code prior to the call:

```
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
```

But then the request will timeout and I am unsure why. I get the error: 
```
async_sendmessage: Exceeding MAX_RETRIES, abandoning send
```

I am able to recreate the error with:

```
import Thread
import asyncio

def test():
    # asyncio.set_event_loop(asyncio.new_event_loop()) # <- try with & without this commented out to see both issues
    link.turn_on_by_featureset_id(featureId)

thread = Thread(target=test)
thread.start()
```

**Comment by alfiedouglas-tewke** [comment]
This can also be recreated by modifying all the non-async methods slightly:

```
    #########################################################
    # Convenience methods for non-async calls
    #########################################################

    @staticmethod
    def get_or_create_eventloop():
        try:
            return asyncio.get_event_loop()
        except RuntimeError as ex:
            if "There is no current event loop in thread" in str(ex):
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
                return asyncio.get_event_loop()

    def _sendmessage(self, message):
        return self.get_or_create_eventloop().run_until_complete(self._async_sendmessage(message))
   
   ...
```

**Comment by bigbadblunt** [comment]
OK, so I'm not expert in threading and coroutines, and I'm not sure what your use case is, but I managed to get this working across threads as follows:

Your main thread will need to get the details of the event loop

`_loop = asyncio.get_event_loop()`

then when you call the functions you need to use `asyncio.run_coroutine_threadsafe` and pass it the details of the main thread event loop

`asyncio.run_coroutine_threadsafe(link.async_turn_on_by_featureset_id("blah"), _loop)`

Below is a working set of code

```
from lightwave2 import lightwave2
import logging, asyncio
import threading

logging.basicConfig(level=logging.DEBUG)

_loop = asyncio.get_event_loop()
link = lightwave2.LWLink2("user","password")

def test():
    asyncio.run_coroutine_threadsafe(link.async_turn_on_by_featureset_id("blahblah"), _loop)

async def main():
    await link.async_connect()
    await link.async_get_hierarchy()
    thread = threading.Thread(target=test)
    thread.start()
    while True:
        print("looping")
        await asyncio.sleep(1)

_loop.run_until_complete(main())
```

I think the problem in your code is that my library has a mechanism for checking that requests have been received by the lightwave server. This is running continuously on the main event loop. When you create a new event loop in your thread it appears that the code to check transmission stays in a different event loop and is never able to confirm successful transmission. It therefore blocks (and eventually times out). To fix this you need to run the request in the same event loop as was originally used to set up the link. My code above appears to do that. I will caveat that my understanding of this is sketchy, so this might all be nonsense, but it does appear to work.

**Comment by alfiedouglas-tewke** [comment]
@bigbadblunt that's great, really appreciate it - thanks a lot! :)
